language: python
sudo: false

before_install:
  - pip install hererocks
  - source setup.sh
  - eval "$(curl -Ss https://raw.githubusercontent.com/neovim/bot-ci/master/scripts/travis-setup.sh) nightly-x64"

addons:
  apt:
    sources:
      - kalakris-cmake
    packages:
      - cmake

script:
  - busted .
